default_language_version:
  python: python312
default_stages: [pre-commit]

repos:
  # Common pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=20000']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
        args: ['--unsafe']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: '^data/'
        args: ['--autofix']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: debug-statements

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
